# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Humane Raccoon
tagline:          'Website in progress'
description:      'more to come...</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ethan Cramer'
  url:            https://twitter.com/ethan_savoy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/EthanCramer1/Humane-Raccoon-Alternatives
